spring.application.name=Customer
#spring.application.name=OrderService

server.port=8084


# PostgreSQL Database Configuration
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/CUSTOMER
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Log file name
logging.file.name=logs/customer-service.log
# Log level
#logging.level.root=ERROR
logging.level.com.cg.customer=INFO
#logging.level.org.hibernate=ERROR
#logging.level.com.netflix.discovery=ERROR
#logging.level.org.springframework=ERROR
# Redis config

#spring.data.redis.host=lagoon-macrocrisp-sink-71863.db.redis.io:10616
#spring.data.redis.port=10616
#spring.data.redis.username=default
#spring.data.redis.password=AIsZilxYIatPzKsBod24G2s2NMBzVF98



